name: YouOweMe
description: Making it simpler to track those chillars.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rxdart: ^0.23.1
  device_preview: ^0.4.4
  graphql_flutter: ^3.0.1
  provider: ^4.0.5
  cloud_firestore: ^0.13.5

  # Used by Artemis (Code Gen)
  json_serializable: ^3.3.0
  equatable: ^1.1.1
  meta: ^1.1.8
  sliding_up_panel: ^1.0.2
  contacts_service: ^0.4.5
  permission_handler: ^5.0.0+hotfix.3
  fuzzy: ^0.2.3
  firebase_auth: ^0.16.0
  pin_code_text_field: ^1.5.1
  flutter_launcher_icons: ^0.7.5
  animations: ^1.0.0+5
  flutter_staggered_animations: ^0.1.2
  simple_animations: ^2.1.0
  streaming_shared_preferences: ^1.0.1
  firebase_messaging: ^6.0.13
  after_layout: ^1.0.7+2
  basics: ^0.4.0
  retry: ^3.0.0+1
  modal_bottom_sheet: ^0.1.5

dev_dependencies:
  artemis:
    git:
      url: git://github.com/comigor/artemis.git
      ref: ditrty/dedup-fix
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/scribbles/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#F1F5F9"
  adaptive_icon_foreground: "assets/logo.png" 

  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
        - asset: assets/fonts/Aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 500
        - asset: assets/fonts/Aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-Heavy.otf
          weight: 800
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-UltraLightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-ThinItalic.otf
        - asset: assets/fonts/Aileron/Aileron-SemiBoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-HeavyItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf
