name: YouOweMe
description: Making it simpler to track those chillars.

version: 0.0.2

environment:
  sdk: ">2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  device_preview:
    git:
      url: https://github.com/preetjdp/flutter_device_preview.git
      ref: Preet-Custom
      path: device_preview/
  graphql_flutter: ^3.0.1
  hooks_riverpod: ^0.1.0
  flutter_hooks: ^0.10.0
  cloud_firestore: ^0.13.6
  json_serializable: ^3.3.0
  equatable: ^1.2.0
  meta: ^1.1.8
  sliding_up_panel: ^1.0.2
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1
  fuzzy: ^0.2.3
  firebase_auth: ^0.16.1
  pin_code_text_field: ^1.6.0
  flutter_launcher_icons: ^0.7.5
  animations: ^1.1.0
  flutter_staggered_animations: ^0.1.2
  simple_animations: ^2.2.1
  streaming_shared_preferences: ^1.0.1
  firebase_messaging: ^6.0.16
  after_layout: ^1.0.7+2
  basics: ^0.4.0
  retry: ^3.0.0+1
  modal_bottom_sheet: ^0.1.6+1
  firebase_analytics: ^5.0.15
  firebase_dynamic_links: ^0.5.1
  rough: ^0.1.1

dev_dependencies:
  import_sorter: ^3.1.0
  artemis:
    git:
      url: git://github.com/comigor/artemis.git
      ref: ditrty/dedup-fix
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/scribbles/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#F1F5F9"
  adaptive_icon_foreground: "assets/logo.png"

  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
        - asset: assets/fonts/Aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 500
        - asset: assets/fonts/Aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-Heavy.otf
          weight: 800
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-UltraLightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-ThinItalic.otf
        - asset: assets/fonts/Aileron/Aileron-SemiBoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-HeavyItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf

import_sorter:
  emojis: true
  ignored_files:
    - /lib\resources\graphql\seva.dart
    - /lib\resources\graphql\seva.graphql.dart
    - /lib\resources\graphql\seva.graphql.g.dart
    - /lib\generated_plugin_registrant.dart
